spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: vehicle-service
  data:
    redis:
      port: 6379
      host: 172.17.0.1
  kafka:
    bootstrap-servers: 172.17.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 18081
