version: '3.8'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master-service
    ports:
      - "18080:18080"
    networks:
      - local-network

networks:
  local-network:
    external: true